# Generated by Django 5.0.6 on 2024-06-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(default=2, verbose_name=[(1, 'Забронировано'), (3, 'Отменено'), (2, 'Доступно')]),
        ),
    ]
