# Generated by Django 5.0.6 on 2024-06-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0006_remove_reports_created_at_alter_reports_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='creates_at',
        ),
    ]
